services:
#   pyspark:
#     image: quay.io/jupyter/pyspark-notebook
#     container_name: pyspark
#     ports:
#       - "8888:8888"
#       - "4040-4042:4040-4042"
#     volumes:
#       - ${PWD}:/home/jovyan/work
#       - ${PWD}/project-data:/home/jovyan/project-data
#     environment:
#       JUPYTER_ENABLE_LAB: "yes"
#     networks:
#       - net

  postgres:
    image: postgres:17
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
     -   ${PWD}:/scripts
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    networks:
      - net

networks:
  net:
    driver: bridge
